CREATE TABLE IF NOT EXISTS `itens` (
	`id_solicitacao`	INTEGER NOT NULL,
	`id_item`	INTEGER NOT NULL,
	`nomeItem`	TEXT NOT NULL,
	`descricao`	TEXT,
	`categoria`	TEXT NOT NULL,
	`classificacao`	INTEGER NOT NULL,
	`quantidade`	INTEGER NOT NULL,
	`unidade`	TEXT NOT NULL,
	PRIMARY KEY(`id_item` AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS `cotacao` (
	`id_cotacao`	INTEGER NOT NULL,
	`id_solicitacao`	INTEGER NOT NULL,
	`usuario`	TEXT NOT NULL,
	`fornecedor`	TEXT NOT NULL,
	`contato_fornecedor`	TEXT DEFAULT 'Ñ preenchido',
	`quantidade`	INTEGER NOT NULL,
	`unidade`	TEXT DEFAULT 'Ñ preenchido',
	`valor_un`	INTEGER NOT NULL,
	`valor_total`	INTEGER NOT NULL,
	`frete`	INTEGER,
	`inf_extra`	TEXT,
	`validade_cotacao`	TEXT DEFAULT 'Ñ preenchido',
	`status_cotacao`	INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY(`id_cotacao` AUTOINCREMENT),
	FOREIGN KEY(`id_solicitacao`) REFERENCES `solicitacao`(`id_solicitacao`)
);
CREATE TABLE IF NOT EXISTS `solicitacao` (
	`id_solicitacao`	INTEGER NOT NULL,
	`solicitante`	TEXT NOT NULL,
	`data`	TEXT NOT NULL,
	`motivo`	TEXT NOT NULL,
	`qnt_itens`	INTEGER NOT NULL,
	`setor`	TEXT NOT NULL,
	`prioridade`	TEXT NOT NULL,
	`qnt_cotacao`	INTEGER NOT NULL DEFAULT 0,
	`status`	INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY(`id_solicitacao` AUTOINCREMENT)
);
INSERT INTO `itens` (`id_solicitacao`,`id_item`,`nomeItem`,`descricao`,`categoria`,`classificacao`,`quantidade`,`unidade`) VALUES (11,1,'Qqqq','qqq','Componente','Investimento',111,'Bloco'),
 (11,2,'Www','www','EPI','Obra/Infraestrutura',222,'Bobina'),
 (12,3,'SUelen','Sandro','MP','Serviço - Manutenção Planejada',100,'Conjunto'),
 (13,4,'caneta','quero uma caneta azul','Escritório','Investimento',1,'Unidade'),
 (2,5,'Frederico',NULL,'',0,0,''),
 (14,6,'AAAAAAAAAAAAAAAA','AAAAAAAAAAAAAAAA','Material de Consumo','Obra/Infraestrutura',11,'Frasco'),
 (14,7,'BBB','BBB','Material de Consumo','Obra/Infraestrutura',222,'Folha'),
 (14,8,'CCC','CCC','Material de Consumo','Obra/Infraestrutura',333,'Galão'),
 (14,9,'DDD','DDD','EPI','Material Novo - Manutenção Planejada',555,'Frasco'),
 (14,10,'EEE','EEE','Material de Manutenção','Material Novo - Manutenção Corretiva',555,'Conjunto'),
 (15,11,'Coleira','Frederico','EPI','Obra/Infraestrutura',50,'Unidade'),
 (15,12,'Garrafa PET','Para os cachorros','Material de Consumo','Material Novo - Manutenção Planejada',1,'Unidade'),
 (15,13,'Creme para patas','Bisbique','EPI','Investimento',200,'Litro');
INSERT INTO `solicitacao` (`id_solicitacao`,`solicitante`,`data`,`motivo`,`qnt_itens`,`setor`,`prioridade`,`qnt_cotacao`,`status`) VALUES (1,'processo','31/01/2023','sssss',1,'Produto Próprio','Baixa',0,1),
 (2,'processo','31/01/2023','Jju',1,'Qualidade','Baixa',0,2),
 (3,'processo','31/01/2023','Jjj',1,'Manutenção','Baixa',0,2),
 (4,'processo','31/01/2023','I''m ',1,'Produto Próprio','Baixa',0,1),
 (5,'processo','31/01/2023','K',1,'MC Ajustagem','Baixa',0,1),
 (6,'processo','31/01/2023','Iikk',1,'Sala Branca','Baixa',0,2),
 (7,'processo','31/01/2023','Kk',1,'MC Laminação','Baixa',0,2),
 (8,'processo','31/01/2023','Mk',1,'Qualidade','Baixa',0,2),
 (9,'processo','31/01/2023','Kkk',1,'Qualidade','Baixa',0,2),
 (10,'processo','31/01/2023','Ii',3,'Colmeia','Baixa',0,2),
 (11,'processo','31/01/2023','Qqq',2,'Administração','Alta',0,0),
 (12,'teste','01/02/2023','Por que sim',1,'Produto Próprio','Alta',0,1),
 (13,'processo','01/02/2023','por que eu quero',1,'Administração','Baixa',0,1),
 (14,'processo','03/02/2023','AAAAAAAAAAAAAAAA',5,'Qualidade','Média',0,1),
 (15,'teste','03/02/2023','Compra mensal',3,'Qualidade','Média',0,2),
 (16,'teste','04/02/2023','Jjjj',1,'Produto Próprio','Média',0,0),
 (17,'processo','04/02/2023','qq',1,'Qualidade','Média',0,0);
COMMIT;
